### PR TITLE
Setting logbook data folder

### PR DESCRIPTION
**Pull request by Rasbats**
Plus icon show.

Needs fully testing before release. I have no existing logbooks to test against.

### CODE REVIEW

**Comment by rgleason** [comment]
Mike, thanks so much!

Way down at load layouts 
	data.append(sep);
    data.Append( _T("data"));

Will merge and test

**Comment by rgleason** [comment]
Mike,
I realize that the PR did not show all the changes for some reason.

We do still need  the use of this function because it provides a user writable data directory which is necessary for the layouts to work properly and for users to save their changes.

//  wxString stdPath( GetpPrivateApplicationDataLocation());

However the PR does show how to fix the logbook/data instead of logbookdata issue.
I may try to unwind this.   Actually I am working in the master-updateFE branch.

**Comment by rgleason** [comment]
Also do you know what this change does?
-    m_bpButtonShowHideLayout->SetToolTip( panelOnOff[!logbookPlugIn->opt->layoutShow] );
+    m_bpButtonShowHideLayout->SetToolTip( panelOnOff[!logbookPlugIn->show] );

**Comment by Rasbats** [comment]
>Also do you know what this change does?

Right arrow at the top of the Logbook dialog. Toggles 'Show Engines/Sails Mode'. Allows user to record engine off/on and the sails in use.

**Comment by Rasbats** [comment]
>// wxString stdPath( GetpPrivateApplicationDataLocation());

In the function: 'wxString logbookkonni_pi::StandardPath( void )'
If you uncomment this line StandardPath() will return 'ProgramData/opencpn' and not 'ProgramData/opencpn/plugins/logbook'

**Comment by rgleason** [comment]
Ok I am stumped, where is StandardPath() set using  GetpPrivateApplicationDataLocation()); ?
Alec said we needed to use that to fix the plugin.

**Comment by rgleason** [comment]
I built and installed  v1.4.13.18  and it appears to be using the  %localappdata%\opencpn\plugins\logbookkonni_pi\data\logbook.txt

image

Which does not allow a user to save their data.

**Comment by rgleason** [comment]
I will try to fix this later. Thanks you've provided me with the way to do that.  May have a question later.

**Pull request merged**
